from .models import Page
from django.db.models import Q

def _get_query_set(q: str):
    """Generates the Q model from the query given
    Returns the ``django.db.models.Q`` object.
    the Q object is generated by using OR on space seperated
    keywords of query
    TODO: add the functionality for AND, NOT in Q objects
    """

    q = q.split(' ')
    ret = Q()
    for i in q:
        ret = ret | Q(content__search=i)
    return ret

def get_search_results(query: str):
    """This is a helper function that returns the search
    result of the query over the Page model.
    This function returns a queryset that contains all the Page results
    """

    return Page.objects.filter(_get_query_set(query))