# Generated by Django 2.1.7 on 2019-06-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('numpages', models.CharField(default='', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/')),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('book_pdf', models.FileField(blank=True, upload_to='book_pdf')),
                ('book_content', models.FileField(blank=True, upload_to='book_page_content')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetitle', models.CharField(default='', max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='page_images/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='home.Book')),
            ],
        ),
    ]
