# Generated by Django 2.1.7 on 2019-04-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='page_images/'),
        ),
    ]
