# Generated by Django 2.1.7 on 2019-04-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_page_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
