# Generated by Django 2.1.7 on 2019-08-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_segment',
            field=models.FileField(blank=True, upload_to='book_segment'),
        ),
        migrations.AddField(
            model_name='page',
            name='segment',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
