# Generated by Django 2.1.7 on 2019-05-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190427_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_content',
            field=models.FileField(blank=True, upload_to='book_page_content'),
        ),
    ]
