# Generated by Django 2.1.7 on 2019-06-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_book_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='home.Page'),
        ),
    ]
